//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasirPal
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Банковские_данные__
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_Банковские_данные__()
        {
            this.Сотрудники_ = new HashSet<Сотрудники_>();
        }
    
        public int Код { get; set; }
        public string Рассчетный_счет { get; set; }
        public string БИК { get; set; }
        public string к_с { get; set; }
        public string ИНН { get; set; }
        public string КПП { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Сотрудники_> Сотрудники_ { get; set; }
    }
}
