//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasirPal
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Прием_материала__
    {
        public int Код_ { get; set; }
        public Nullable<int> Код_поставщика { get; set; }
        public Nullable<int> Код_материала { get; set; }
        public Nullable<int> Количество { get; set; }
    
        public virtual Материалы_ Материалы_ { get; set; }
        public virtual Поставщики_ Поставщики_ { get; set; }
    }
}
