//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasirPal
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Рейтинг_партнеров__
    {
        public int Код { get; set; }
        public Nullable<int> Код_партнера { get; set; }
        public Nullable<int> Место_в_рейтинге { get; set; }
        public Nullable<System.DateTime> Дата_обновления { get; set; }
    
        public virtual Партнеры_ Партнеры_ { get; set; }
    }
}
