//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasirPal
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Тип_материала__
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_Тип_материала__()
        {
            this.Материалы_ = new HashSet<Материалы_>();
        }
    
        public int Код { get; set; }
        public string Наименование { get; set; }
        public Nullable<double> Коэффицент_типа_материала { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Материалы_> Материалы_ { get; set; }
    }
}
