//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasirPal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class upeshkaEntities : DbContext
    {
        public upeshkaEntities()
            : base("name=upeshkaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_Банковские_данные__> C_Банковские_данные__ { get; set; }
        public virtual DbSet<Должность_> Должность_ { get; set; }
        public virtual DbSet<C_Доступ_кадров_к_оборудованию__> C_Доступ_кадров_к_оборудованию__ { get; set; }
        public virtual DbSet<C_Единицы_измерения__> C_Единицы_измерения__ { get; set; }
        public virtual DbSet<Заявки_> Заявки_ { get; set; }
        public virtual DbSet<C_История_прохода_через_турникет__> C_История_прохода_через_турникет__ { get; set; }
        public virtual DbSet<C_Количество_материала__> C_Количество_материала__ { get; set; }
        public virtual DbSet<Материалы_> Материалы_ { get; set; }
        public virtual DbSet<C_Места_продаж_партнеров__> C_Места_продаж_партнеров__ { get; set; }
        public virtual DbSet<Наличие_семьи> Наличие_семьи { get; set; }
        public virtual DbSet<C_Номер_стандарта__> C_Номер_стандарта__ { get; set; }
        public virtual DbSet<Оборудование_> Оборудование_ { get; set; }
        public virtual DbSet<Оплата_> Оплата_ { get; set; }
        public virtual DbSet<Партнеры_> Партнеры_ { get; set; }
        public virtual DbSet<Поставщики_> Поставщики_ { get; set; }
        public virtual DbSet<C_Прием_материала__> C_Прием_материала__ { get; set; }
        public virtual DbSet<C_Продукции_на_складе__> C_Продукции_на_складе__ { get; set; }
        public virtual DbSet<C_Продукция_к_заявке__> C_Продукция_к_заявке__ { get; set; }
        public virtual DbSet<Продукция_> Продукция_ { get; set; }
        public virtual DbSet<C_Размер_упаковки__> C_Размер_упаковки__ { get; set; }
        public virtual DbSet<Реализация_продукции_> Реализация_продукции_ { get; set; }
        public virtual DbSet<C_Рейтинг_партнеров__> C_Рейтинг_партнеров__ { get; set; }
        public virtual DbSet<C_Сертификат_качества__> C_Сертификат_качества__ { get; set; }
        public virtual DbSet<Склад_> Склад_ { get; set; }
        public virtual DbSet<C_Состав_продукции__> C_Состав_продукции__ { get; set; }
        public virtual DbSet<C_Состояние_здоровья__> C_Состояние_здоровья__ { get; set; }
        public virtual DbSet<Сотрудники_> Сотрудники_ { get; set; }
        public virtual DbSet<C_Способ_оплаты__> C_Способ_оплаты__ { get; set; }
        public virtual DbSet<C_Статус_заявки__> C_Статус_заявки__ { get; set; }
        public virtual DbSet<C_Тип_материала__> C_Тип_материала__ { get; set; }
        public virtual DbSet<C_Тип_партнера__> C_Тип_партнера__ { get; set; }
        public virtual DbSet<C_Тип_поставщика__> C_Тип_поставщика__ { get; set; }
        public virtual DbSet<C_Тип_продукции__> C_Тип_продукции__ { get; set; }
        public virtual DbSet<Цех_> Цех_ { get; set; }
    }
}
