//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasirPal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявки_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заявки_()
        {
            this.Оплата_ = new HashSet<Оплата_>();
        }
    
        public int Код { get; set; }
        public Nullable<int> Код_партнера { get; set; }
        public Nullable<System.DateTime> Дата_создания { get; set; }
        public Nullable<int> Код_статуса { get; set; }
        public Nullable<int> Предоплата { get; set; }
        public Nullable<int> Сумма { get; set; }
        public Nullable<int> Код_продукции_к_заявке { get; set; }
    
        public virtual C_Продукция_к_заявке__ C_Продукция_к_заявке__ { get; set; }
        public virtual C_Статус_заявки__ C_Статус_заявки__ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Оплата_> Оплата_ { get; set; }
    }
}
