//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasirPal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Материалы_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Материалы_()
        {
            this.C_Количество_материала__ = new HashSet<C_Количество_материала__>();
            this.C_Прием_материала__ = new HashSet<C_Прием_материала__>();
            this.C_Состав_продукции__ = new HashSet<C_Состав_продукции__>();
        }
    
        public int Код { get; set; }
        public Nullable<int> Тип_материала { get; set; }
        public string Наименование { get; set; }
        public Nullable<int> Количество_в_упаковке { get; set; }
        public Nullable<int> Код_единицы_измерения { get; set; }
        public string Описание { get; set; }
        public string Изображение { get; set; }
        public Nullable<int> Стоимость { get; set; }
        public Nullable<int> Минимальное_допустимое_количество { get; set; }
    
        public virtual C_Единицы_измерения__ C_Единицы_измерения__ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Количество_материала__> C_Количество_материала__ { get; set; }
        public virtual C_Тип_материала__ C_Тип_материала__ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Прием_материала__> C_Прием_материала__ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Состав_продукции__> C_Состав_продукции__ { get; set; }
    }
}
