//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasirPal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оплата_
    {
        public int Код { get; set; }
        public Nullable<int> Код_заявки { get; set; }
        public Nullable<int> Сумма { get; set; }
        public Nullable<System.DateTime> Дата_оплаты { get; set; }
        public Nullable<int> Код_способа_оплаты { get; set; }
    
        public virtual Заявки_ Заявки_ { get; set; }
        public virtual C_Способ_оплаты__ C_Способ_оплаты__ { get; set; }
    }
}
