//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasirPal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Партнеры_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Партнеры_()
        {
            this.C_Места_продаж_партнеров__ = new HashSet<C_Места_продаж_партнеров__>();
            this.Реализация_продукции_ = new HashSet<Реализация_продукции_>();
            this.C_Рейтинг_партнеров__ = new HashSet<C_Рейтинг_партнеров__>();
        }
    
        public int Код { get; set; }
        public Nullable<int> Тип_партнера { get; set; }
        public string Наименование_партнера { get; set; }
        public string Фамилия_директора { get; set; }
        public string Отчество_директора { get; set; }
        public string Имя_директора { get; set; }
        public string Электронная_почта_партнера { get; set; }
        public string Телефон_партнера { get; set; }
        public string Юридический_адрес_партнера { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Места_продаж_партнеров__> C_Места_продаж_партнеров__ { get; set; }
        public virtual C_Тип_партнера__ C_Тип_партнера__ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Реализация_продукции_> Реализация_продукции_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Рейтинг_партнеров__> C_Рейтинг_партнеров__ { get; set; }
    }
}
