//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasirPal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Поставщики_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Поставщики_()
        {
            this.C_Прием_материала__ = new HashSet<C_Прием_материала__>();
        }
    
        public int Код { get; set; }
        public Nullable<int> Код_типа_поставщика { get; set; }
        public string Наименование { get; set; }
        public string ИНН { get; set; }
    
        public virtual C_Тип_поставщика__ C_Тип_поставщика__ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Прием_материала__> C_Прием_материала__ { get; set; }
    }
}
