//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasirPal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продукция_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Продукция_()
        {
            this.C_Продукции_на_складе__ = new HashSet<C_Продукции_на_складе__>();
            this.C_Продукция_к_заявке__ = new HashSet<C_Продукция_к_заявке__>();
            this.Реализация_продукции_ = new HashSet<Реализация_продукции_>();
            this.C_Состав_продукции__ = new HashSet<C_Состав_продукции__>();
        }
    
        public int Код { get; set; }
        public Nullable<int> Код_типа_продукции { get; set; }
        public string Наименование { get; set; }
        public string Артикул { get; set; }
        public Nullable<int> Минимальная_стоимость { get; set; }
        public Nullable<int> Код_размера_упаковки { get; set; }
        public string Описание { get; set; }
        public string Изображение { get; set; }
        public Nullable<double> Вес_без_упаковки { get; set; }
        public Nullable<double> Вес_с_упаковкой { get; set; }
        public Nullable<int> Код_сертификата { get; set; }
        public Nullable<int> Код_номера_стандарта { get; set; }
        public Nullable<double> Время_изготовления { get; set; }
        public Nullable<int> Себестоимость { get; set; }
        public Nullable<int> Код_цеха { get; set; }
        public Nullable<int> Количество_человек_на_производтстве { get; set; }
        public Nullable<int> Код_склада { get; set; }
    
        public virtual C_Номер_стандарта__ C_Номер_стандарта__ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Продукции_на_складе__> C_Продукции_на_складе__ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Продукция_к_заявке__> C_Продукция_к_заявке__ { get; set; }
        public virtual C_Размер_упаковки__ C_Размер_упаковки__ { get; set; }
        public virtual C_Сертификат_качества__ C_Сертификат_качества__ { get; set; }
        public virtual Склад_ Склад_ { get; set; }
        public virtual C_Тип_продукции__ C_Тип_продукции__ { get; set; }
        public virtual Цех_ Цех_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Реализация_продукции_> Реализация_продукции_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Состав_продукции__> C_Состав_продукции__ { get; set; }
    }
}
