//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasirPal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Реализация_продукции_
    {
        public int Код { get; set; }
        public Nullable<int> Код_продукции { get; set; }
        public Nullable<int> Код_партнера { get; set; }
        public Nullable<int> Количество_продукции { get; set; }
        public Nullable<System.DateTime> Дата_продажи { get; set; }
    
        public virtual Партнеры_ Партнеры_ { get; set; }
        public virtual Продукция_ Продукция_ { get; set; }
    }
}
