//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasirPal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сотрудники_()
        {
            this.C_Доступ_кадров_к_оборудованию__ = new HashSet<C_Доступ_кадров_к_оборудованию__>();
            this.C_История_прохода_через_турникет__ = new HashSet<C_История_прохода_через_турникет__>();
        }
    
        public int Код { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
        public string Серия_паспорта { get; set; }
        public string Номер_паспорта { get; set; }
        public Nullable<int> Код_наличия_семьи { get; set; }
        public Nullable<int> Код_состояния_здоровья { get; set; }
        public Nullable<int> Код_должности { get; set; }
        public Nullable<int> Код_банковских_данных { get; set; }
    
        public virtual C_Банковские_данные__ C_Банковские_данные__ { get; set; }
        public virtual Должность_ Должность_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Доступ_кадров_к_оборудованию__> C_Доступ_кадров_к_оборудованию__ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_История_прохода_через_турникет__> C_История_прохода_через_турникет__ { get; set; }
        public virtual Наличие_семьи Наличие_семьи { get; set; }
        public virtual C_Состояние_здоровья__ C_Состояние_здоровья__ { get; set; }
    }
}
